
name: streamlit-example

channels:
- conda-forge

dependencies:
- altair >= 4.1.0
- flake8 >= 4.0.1
- isort >= 5.9.3
- numpy >= 1.21.3
- pandas >= 1.2.5
- pillow >= 8.3.2
- py-opencv >= 4.5.3
- python >= 3.9.7
- ruamel.yaml >= 0.17.16
- streamlit >= 1.1.0
